### PR TITLE
Homepage header + widgets

### PR DESCRIPTION
**Pull request by yingles**
This is a very rough setup of the homepage + widgets.

Testing out using an Image widget for the main image with the `wcus-background.jpg` image (in assets) at full size. Then doing some `object-fit` so the size is determined by the logo + text widgets.

Logo and text are made from a custom HTML widget with the following markup:

```
<div id="wcus-hp-widgets">
	<div class="wcus-hp-circle">
	    <a href="#" class="wcus-hp-logo">WCUS Logo</a>
		<div class="wcus-hp-message">
			<h2>
				3 days, 50+ sessions, & the City Museum
			</h2>
			<p>
				WordCamp U.S. has something for everyone.
			</p>
		</div>
        <a class="wcus-hp-signup">
            Sign Up
        </a>
	</div>
</div>
```

Its rough and needs a clean-up pass through the CSS, but I wanted to get some thoughts on handling the main blue circle for resizing and as the text breaks to multiple lines.

Screen Shot 2019-04-25 at 12 27 18 AM

### CODE REVIEW

**Comment by yingles** [comment]
This is for #27 

Feel free to grab it and revamp. I'm not going to be able until after Thursday (4/25).

**Comment by ryelle** [comment]
I can take a pass at this tomorrow (fri) morning– I think we can get away with just adding a background image to the custom HTML widget, since this image probably won't need to be changed.

**Comment by ryelle** [comment]
I'm still working on this but need to break for a bit– I updated the HTML for the widget to this (and you only need the one custom HTML widget now):

```html
<div id="wcus-hero">
	<div class="wcus-hero__circle">
		<div class="wcus-hero__logo wcus-hero__circle-small" aria-hidden></div>
		<div class="wcus-hero__message">
			<h2>3 days, 50+ sessions, &amp;&nbsp;the City Museum</h2>
			<p>WordCamp U.S. has something for&nbsp;everyone.</p>
		</div>
		<a class="wcus-hero__signup wcus-hero__circle-small" href="/tickets">
			<span>Sign Up</span>
		</a>
	</div>
</div>
```

**Comment by ryelle** [comment]
Updated PR now looks like this:

Screen Shot 2019-04-26 at 7 10 46 PM

And some tweaks for larger phones/tablets (will probably need more thought for 480 and below)

Screen Shot 2019-04-26 at 7 11 09 PM

I'm also not sure what to do about focus on the Sign Up link

`outline` doesn't respect border-radius, so it looks wonky:

outline

We could add a dotted border, but then we can't outset it:

border-current

What I landed on in this PR is just a small border under the Sign Up text.

border

I know @melchoyce had some light animation effects in mind for the hover state, but she's out for the evening already -- we can follow up with that in another PR if we need.

**Comment by yingles** [comment]
Looking good @ryelle. I'm just having an issue with the image not going all the way to the left. 

image

**Comment by yingles** [comment]
Seems like it's something with being inside the `<header>` that is `display: flex;`. Looks like moving only the `margin-left: calc(50% - 50vw);` onto `#header-widgets` fixes it on my end.

**Comment by ryelle** [comment]
Sounds like your widget is in the wrong place– it should be in "Before Content (Homepage) Area 1", so that is only shows up on the homepage.

**Comment by yingles** [comment]
> Sounds like your widget is in the wrong place– it should be in "Before Content (Homepage) Area 1", so that is only shows up on the homepage.

Yep. You're right. Good to merge. Leaving open until the header widgets PR can be merged in.

**Comment by ryelle** [comment]
This can be merged, we shouldn't need to wait for #30

**Pull request merged**
