### PR TITLE
Add Sponsors style

### PR DESCRIPTION
**Pull request by ryelle**
This PR adds the sponsor style from #7 to the footer widget and the sponsors list page. For the page, it should use this shortcode:

`[sponsors link="post" title="none" content="none"]`

For widgets, it's "Footer Area 1" with the Sponsors widget and a custom HTML widget with the following HTML

```html
<a href="/sponsors" class="cta-button">Learn more about our sponsors</a>
```

In the footer, this looks like:

Screen Shot 2019-04-16 at 7 24 42 PM

And on the sponsors page:

Screen Shot 2019-04-16 at 7 24 57 PM

### CODE REVIEW

**Comment by melchoyce** [comment]
Hover/focus styles for the sponsors:

image

Background color on hover is `#F1F1EA`, and focus would match the button focus styles.

**Comment by ryelle** [comment]
Updated the hover & focus styles.

**Comment by yingles** [comment]
We probably need to do up the sizes on the logos for mobile. Maybe reduce the padding in the box and decrease the grid gaps?

**Comment by ryelle** [comment]
I've tweaked the padding & grid-gap, and @melchoyce has given this the ✅  I'm going to merge this so we can cut down on the open PRs.

**Pull request merged**
