### PR TITLE
Style homepage widgets

### LINKED ISSUE #29: Homepage Widgets
image

SVGs: https://cloudup.com/ctRFnF0ZH-D

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #29 , note that this is based on #27 

desktop

On tablet-sized screens:

tablet

This assumes 1 widget in "Before Content (Homepage) Area 2", a text widget:

```html
November 1–3, 2019

America's Center, St. Louis, MO
```

And 4 Custom HTML widgets in "Before Content (Homepage) Area 3", with variations on this, using SVGs from the wc-us.org site.

```html
<a href="#">
<img src="https://wc-us.org/wp-content/uploads/2019/04/home-info.svg" alt="" />
Practical Info</a>
```

### CODE REVIEW

**Comment by melchoyce** [comment]
Turns out I don’t like the hover effect on these in practice. Can we darken the background instead of changing the icon color and adding an underline, and add a shadow (the same as the one on the sign up circle)?

image

**Comment by ryelle** [comment]
Added shadow, and the dotted border on focus (2nd is focused, last is hovered):

Screen Shot 2019-04-29 at 10 20 42 AM

**Comment by melchoyce** [comment]
Can the shadow function accept a color variable so we can change it based on context?

**Comment by ryelle** [comment]
Yeah, since we're reusing the same shadow a few times we can make it a mixin and accept color. I actually want to do the same for the focus style too…

**Comment by melchoyce** [comment]
Cool — maybe something like $color + darken 20%

**Comment by ryelle** [comment]
OK, new `shadow` mixin which just does the correct spacing with the default (`$dark-brown`) color of shadow. The widgets pass in a custom color, so this is what each look like hovered (1, 3, and 4 are hovered)

Screen Shot 2019-04-29 at 4 01 49 PM

There's also a new `dotted-outline` mixin which does the offset dotted focus style, and also accepts a color.

**Comment by ryelle** [comment]
Merging this so we can iterate on it

**Pull request merged**
